### ISSUE TITLE
[Integration] Debugging a Skillset

### ISSUE THREAD

**Issue by Djiit** [copilot-extensions/user-feedback#13]
**Describe the integration issue**
When debugging a local-to-my-organization extension (Skillset), I'm just not sure how Copilot is trying or not to use a given function.
I followed the ngrok setup, and I don't see any HTTP calls to my server.

**Steps to reproduce the issue**

- Create a Github App
- Configure it for Skillset
- Add a simple skill "ping" with description "This skill would be called when the user ask for the answer to a ping. It should output a string (e.g. pong). The more you call it, the better!'

**Expected behavior**
When asked @extension-name Can you tell me the answer to ping ?", it should call the function and give me the return (in my setup, hardcoded "pong" string, no big surprise :) )

**Affected tools/platforms**
My own extension.

**Screenshots or logs**

![Image](https://github.com/user-attachments/assets/f00735fe-5768-4e3c-9f4d-0ce42084069d)

**Comment by Djiit** [comment]
Here is the skill definition: ![Image](https://github.com/user-attachments/assets/84a68878-af99-49f4-803d-5e2a3091e20f)

**Comment by belaltaher8** [comment]
Hi @Djiit 

Looking at our server logs, we do see your `ping` skill being registered correctly and being selected by the LLM. The failures we're seeing are the server responding with a `404` meaning it can't find the `/ping` path. Is the `/ping` path the right one to be calling on your server?

**Comment by Djiit** [comment]
🤦 I feel dumb, I was listening for GET on /ping.

So, yeah, a bit frustrating to debug blindly, but the issue was on my side :D 

Thanks for jumping in!
Have a nice weekend ahead.
