### ISSUE TITLE
Receive referenced files payload from the IDE possible?

### ISSUE THREAD

**Issue by gsamcalero** [copilot-extensions/user-feedback#9]
**Question**
Are the referenced files in the VSCode or the Visual Studio 2022 GitHub Copilot extensions sent with the HTTP request? I tried the blackbeard-extension demo and the received payload contains the text message history including several other metadata details, but I could not get the attached/referenced files to get posted with the rest of the payload. Is this an unsupported feature for copilot extensions at the moment?

Example in VSCode:
![Image](https://github.com/user-attachments/assets/3f23147d-27a8-4ef4-9a5e-4a936af63cab)

VS2022 has a similar UI element:
![Image](https://github.com/user-attachments/assets/31e0d9f4-cc4c-433a-be08-652f96ffcc35)

**Context**
blackbeard-extension github copilot extension sample.

**Additional context**
Main test in VSCode with GitHub Copilot extension v1.246.0, GitHub App created and configured with ngrok for local testing.

**Comment by yuqizhou77** [comment]
I have same question. Hoping someone can help :)

**Comment by theodoracheng** [comment]
👋 Hello, this is a great question and is relevant to a new feature we're shipping today! (docs and changelog en route)

For GitHub Copilot Extensions to receive permissions, they will need to enable this new permissions policy
![Image](https://github.com/user-attachments/assets/63bd9f4a-468d-4f61-b000-e8a732268650)

Additionally, to make it more clear when an extension has access to a referenced file, we now will send a warning message to let users know if a reference was redacted in the first message of a thread. Essentially, if a resource's (such as a repo) visibility is set to private, then the account that owns that repo must install the extension and give permission to that repo.

For example:
1. If repo X is owned by individual A, then the individual A will need to install the extension and allow permissions to repo X ([doc](https://docs.github.com/en/enterprise-cloud@latest/apps/using-github-apps/installing-a-github-app-from-a-third-party))
2. If repo Y is owned by org B, then an org B admin will need to install the extension and allow permissions to repo y ([doc](https://docs.github.com/en/enterprise-cloud@latest/apps/using-github-apps/requesting-a-github-app-from-your-organization-owner))
![Image](https://github.com/user-attachments/assets/3fecb387-47b1-4ee7-95fe-fdf019fe3656)

Please let us know if that helped clear up any confusion! We're doing our best to help our builders and users in how context passing works, so we welcome any feedback!

**Comment by gsamcalero** [comment]
Thank you! I can verify that content selection as well as referenced files work in VSCode :)
